version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-me}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
      DJANGO_RUN_SEED: ${DJANGO_RUN_SEED:-False}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST:-postgres}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT:-5432}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME:-postgres}
      DJANGO_DB_USER: ${DJANGO_DB_USER:-postgres}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD:-postgres}
      DJANGO_MEDIA_ROOT: ${DJANGO_MEDIA_ROOT:-/app/media}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
    volumes:
      - staticfiles:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME:-postgres}
      POSTGRES_USER: ${DJANGO_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - staticfiles:/static

volumes:
  staticfiles:
  postgres_data:

