# Generated by Django 4.2.24 on 2025-09-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_announcement_product_promoted_product_promoted_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="end_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="start_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="promoted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="promoted_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
